flix/config/routes.rb
Rails.application.routes.draw do
  resources :users
  
  get 'signup', to: 'users#new'

  root "movies#index"
  resources :movies do
    resources :reviews
  end
end

flix/app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :reviews, dependent: :destroy

  validates :title, presence: true
  
  validates :released_on, :duration, presence: true
  
  validates :description, length: { minimum: 25 }
  
  validates :total_gross, numericality: { greater_than_or_equal_to: 0 }
  
  validates :image_file_name, allow_blank: true, format: {
    with:    /\w+.(gif|jpg|png)\z/i,
    message: "must reference a GIF, JPG, or PNG image"
  }
  
  RATINGS = %w(G PG PG-13 R NC-17)

  validates :rating, inclusion: { in: RATINGS }
  
  def self.released
    where("released_on <= ?", Time.now).order(released_on: :desc)
  end
  
  def self.hits
    where('total_gross >= 300000000').order(total_gross: :desc)
  end
  
  def self.flops
    where('total_gross < 50000000').order(total_gross: :asc)
  end
  
  def flop?
    total_gross.blank? || total_gross < 50000000
  end
  
  def average_stars
    reviews.average(:stars)
  end
end

flix/app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :movie
  
  validates :name, presence: true
  
  validates :comment, length: { minimum: 4 }
  
  STARS = [1, 2, 3, 4, 5]
  
  validates :stars, inclusion: { 
    in: STARS,
    message: "must be between 1 and 5"
  }
end

flix/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :name, presence: true
  validates :email, presence: true,
                    format: {
                        with: /\A\S+@\S+\z/,
                        message: "try another format"
                      },
                    uniqueness: {
                        case_sensitive: false
                      }
  validates :password, length: { minimum: 10, allow_blank: true }
  validates :username, presence: true, uniqueness: { case_sensitive: false },
            format: {with: /\A[A-Z0-9]+\z/i}


end

flix/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

flix/app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.released
  end

  def show
    @movie = Movie.find(params[:id])
  end
  
  def edit
    @movie = Movie.find(params[:id])
  end
  
  def update
    @movie = Movie.find(params[:id])
    if @movie.update(movie_params)
      redirect_to @movie, notice: "Movie successfully updated!"
    else
      render :edit
    end
  end

  def new
    @movie = Movie.new
  end
  
  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to @movie, notice: "Movie successfully created!"
    else
      render :new
    end
  end
  
  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_url, alert: "Movie successfully deleted!"
  end
  
private

  def movie_params
    params.require(:movie).permit(:title, :description, :rating, :released_on, :total_gross, :cast, :director, :duration, :image_file_name)
  end
end

flix/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_movie

  def index
    @reviews = @movie.reviews
  end

  def new
    @review = @movie.reviews.new
  end

  def create
    @review = @movie.reviews.new(review_params)
    if @review.save
      redirect_to movie_reviews_path(@movie),
        notice: "Thanks for your review!"
    else
      render :new
    end
  end
  
private

  def review_params
    params.require(:review).permit(:name, :comment, :stars)
  end

  def set_movie
    @movie = Movie.find(params[:movie_id])
  end

end

flix/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user, notice: "Thanks, #{@user.name} for signing up!"
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user, notice: "Account successfully updated!"
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to root_url, alert: "Account successfully deleted!"
  end

private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :username)
  end
end

flix/app/helpers/application_helper.rb
module ApplicationHelper
end

flix/app/helpers/movies_helper.rb
module MoviesHelper
 def format_total_gross(movie)
   if movie.flop?
    content_tag(:strong, 'Flop!')
   else
     number_to_currency(movie.total_gross)
   end
 end
 
 def image_for(movie)
   if movie.image_file_name.blank?
     image_tag('placeholder.png')
   else
     image_tag(movie.image_file_name)
   end
 end
 
 def format_average_stars(movie)   
   if movie.average_stars.nil?
     content_tag(:strong, 'No reviews')
   else
     pluralize(number_with_precision(movie.average_stars, precision: 1) , 'star')
   end
 end
 
end

flix/app/helpers/reviews_helper.rb
module ReviewsHelper
end

flix/app/helpers/users_helper.rb
module UsersHelper

  def user_grammer
    if (@users.count <= 1)
      "#{@users.count}  User Listed"
    else
      "#{@users.count}  Users Listed"
    end
  end

  def member_since(user)
    user.created_at
  end

  def member_since_format(user)
    member_since(user).strftime("%B, %Y")
  end

end

flix/app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:p, value, :class => "flash #{key}") %>
<% end %>

flix/app/views/layouts/_footer.html.erb
<footer id="page-footer">
  <p>
    Copyright &copy; 2013
    <%= link_to 'The Pragmatic Studio', 'http://pragmaticstudio.com' %>
  </p>
  <p>
    For educational purposes only.
  </p>
</footer>

flix/app/views/layouts/_header.html.erb
<header id="page-header">
  <div id="masthead">
    <h1><%= link_to 'Flix', root_path %></h1>
    <nav>
      <p>
        <%= link_to 'Sign Up', signup_path, class:"button"%>
      </p>
    </nav>
  </div>
</header>

flix/app/views/layouts/_sidebar.html.erb
<aside id="sidebar">
  <nav>
    <ul>
      <li class="movies">
        <%= link_to 'All Movies', movies_path, class: 'button' %>
      </li>
      <li class="create-movie">
        <%= link_to 'Add New Movie', new_movie_path, class: 'button' %>
      </li>
    </ul>
  </nav>
</aside>

flix/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flix</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/header" %>

<div id="wrapper">
  
  <%= render "layouts/flashes" %>
  
  <div id="container">
    <section id="sidebar">
      <%= render "layouts/sidebar" %>
    </section>
    <section id="content">
      <%= yield %>
    </section>
  </div>

</div>

<%= render "layouts/footer" %>

</body>
</html>

flix/app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <%= render "shared/errors", object: @movie %>
  <fieldset>
    <ol>
      <li class="required">
        <%= f.label :title %>
        <%= f.text_field :title, autofocus: true %>
      </li>
      <li class="required">
        <%= f.label :description %>
        <%= f.text_area :description, cols: 40, rows: 7 %>
      </li>
      <li class="required">
        <%= f.label :rating %>
        <%= f.select :rating, Movie::RATINGS, prompt: "Pick one" %>
      </li>
      <li class="required">
        <%= f.label :released_on %>
        <%= f.date_select :released_on %>
      </li>
      <li class="required">
        <%= f.label :total_gross %>
        <%= f.number_field :total_gross %>
      </li>
      <li class="required">
        <%= f.label :duration %>
        <%= f.text_field :duration, size: 10 %>
      </li>
      <li class="required">
        <%= f.label :image_file_name %>
        <%= f.text_field :image_file_name %>
      </li>
      <li>
        <%= f.label :cast %>
        <%= f.text_field :cast %>
      </li>
      <li>
        <%= f.label :director %>
        <%= f.text_field :director %>
      </li>
    </ol>
    <p>
      <%= f.submit %>
      <%= link_to "Cancel", movies_path, class: 'button' %>
    </p>
  </fieldset>
<% end %>

flix/app/views/movies/edit.html.erb
<header id="content-header">
  <h1>Editing <%= @movie.title %></h1>
</header>

<%= render 'form' %>

flix/app/views/movies/index.html.erb
<ul id="movies">
  <% @movies.each do |movie| %>
    <li>
      <article class="movie" id="<%= dom_id(movie) %>">
        <header>
          <%= image_for(movie) %>
          <h2><%= link_to movie.title, movie %> (<%= movie.released_on.year %>)</h2>
          <h3><%= movie.cast %></h3>
        </header>
        <p>
          <%= truncate(movie.description, length: 150, separator: ' ') %>
        </p>
        <table>
          <tr>
            <th>Rating</th>
            <td><%= movie.rating %></td>
          </tr>
          <tr>
            <th>Duration</th>
            <td><%= movie.duration %></td>
          </tr>
          <tr>
            <th>Total Gross</th>
            <td><%= format_total_gross(movie) %></td>
          </tr>
        </table>
        <footer>
        </footer>
      </article>
    </li>
  <% end %>
</ul>

flix/app/views/movies/new.html.erb
<header id="content-header">
  <h1>Create a New Movie</h1>
</header>

<%= render 'form' %>

flix/app/views/movies/show.html.erb
<article id="movie" class="movie">
  <header>
    <%= image_for(@movie) %>
    <h1><%= @movie.title %></h1>
    <h2>Released: <%= @movie.released_on %></h2>
  </header>

  <p>
    <%= @movie.description %>
  </p>
  
  <h3 class="no-rule">
    <%= @movie.rating %> &bull; <%= @movie.duration %> 
  </h3>
  
  <h3>Cast</h3>
  <p>
    <%= @movie.cast %>
  </p>
  
  <h3>Director</h3>
  <p>
    <%= @movie.director %>
  </p>
  
  <h3>Total Gross</h3>
  <p>
    <%= format_total_gross(@movie) %>
  </p>
  
  <h3>Average Review</h3>
  <p>
    <%= format_average_stars(@movie) %>
  </p>
  
  <h3>Reviews</h3>
  <p>
    <%= link_to pluralize(@movie.reviews.size, "review"), 
                  movie_reviews_path(@movie) %>
  </p>
  
  <footer>
    <%= link_to "Write Review", new_movie_review_path(@movie), 
                class: 'button ok review' %>
    <nav>
      <%= link_to 'Edit', edit_movie_path(@movie), class: 'button' %>
      <%= link_to 'Delete', @movie, 
                  class: 'button',
                  method: :delete, data: { confirm: 'Are you sure?' } %>
    </nav>
  </footer>
</article>

flix/app/views/reviews/index.html.erb
<header id="content-header">
  <h1>Reviews for <%= link_to(@movie.title, @movie) %></h2>
</header>

<ol id="reviews">
  <% @reviews.each do |review| %>
    <li>
      <span class="review"><%= pluralize(review.stars, 'star') %></span>
      <span class="user">by <%= review.name %></span>
      <span class="date"><%= time_ago_in_words(review.created_at) %> ago</span>
      <p>
        &quot;<%= review.comment %>&quot;
      </p>
    </li>
  <% end %>
</ol>

flix/app/views/reviews/new.html.erb
<header id="content-header">
  <h1>New Review for <%= link_to @movie.title, @movie %></h2>
</header>

<%= form_for [@movie, @review] do |f| %>
  <%= render "shared/errors", object: @review %>
  <fieldset>
    <ol>
      <li class="required">
        <%= f.label :name %>         
        <%= f.text_field :name, size: 40, autofocus: true %>
      </li>
      <li class="required stars">
        <%= f.label :stars %>
        <% Review::STARS.each do |star| %>
          <span class="star">
            <%= f.radio_button :stars, star %> <%= star %>
          </span>
        <% end %>     
      </li>
      <li class="required">
        <%= f.label :comment %>
        <%= f.text_area :comment, cols: 80, placeholder: "What did you think?" %>
      </li>
    </ol>
    <p>
      <%= f.submit 'Post Review' %> 
      <%= link_to "Cancel", @movie, class: 'button' %>
    </p>
  </fieldset>
<% end %>

flix/app/views/shared/_errors.html.erb
<% if object.errors.any? %>
<section id="errors">
  <header>
    <h2>
      Oops! The <%= object.class.name.titleize.downcase %> could not be saved. 
    </h2>
    <h3>
      Please correct the following <%= pluralize(object.errors.count, "error") %>:
    </h3>
  </header>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</section>
<% end %>

flix/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render "shared/errors", object: @user %>
  <fieldset>
    <ol>
      <li class="required">
        <%= f.label :username %>
        <%= f.text_field :username, size: 40, autofocus: true,
                         placeholder: "Letters and Numbers only!" %>
      </li>
      <li class="required">
        <%= f.label :name %>
        <%= f.text_field :name, size: 40, autofocus: true %>
      </li>
      <li class="required">
        <%= f.label :email %>
        <%= f.email_field :email, size: 40 %>
      </li>
      <li class="required">
        <%= f.label :password %>
        <%= f.password_field :password, size: 40 %>
      </li>
      <li class="required">
        <%= f.label :password_confirmation, "Confirm Password" %>
        <%= f.password_field :password_confirmation, size: 40 %>
      </li>
    </ol>
    <p>
      <% if @user.new_record? %>
        <%= f.submit "Create Account" %>
      <% else %>
        <%= f.submit "Update Account" %>
      <% end %>
    </p>
  </fieldset>
<% end %>

flix/app/views/users/edit.html.erb
<header id="content-header">
  <h1>Edit Account</h1>
</header>

<%= render "form" %>

flix/app/views/users/index.html.erb
<div>
  <article id="user">
    <h1>
      <%= user_grammer %>
    </h1>
    <div>
      <% @users.each do |user| %>

        <div>
          <h2>
            <%= user.name %>
          </h2>
          <h3>
            <%= user.email%>
          </h3>
        </div>
        <div>
          <p>
            <%= link_to "Show #{user.name}", user_path(user)%>
          </p>
        </div>
      <% end %>
    </div>
  </article>
</div>

flix/app/views/users/new.html.erb
<header id="content-header">
  <h1>Sign Up</h1>
</header>

<%= render "form" %>

flix/app/views/users/show.html.erb
<div>
  <article id="user">
    <header>
      <h1>
        <%= @user.name %>
      </h1>
      <h3>Member Since</h3>
      <p>
        <%= member_since_format(@user)%>
      </p>
      <h2>
        <%= mail_to(@user.email) %>
      </h2>
    </header>
  </article>
  <footer>
    <nav>
      <%= link_to 'Edit Account', edit_user_path(@user), class: 'button' %>
      <%= link_to 'Delete Account', @user, method: :delete,
                  data: { confirm: "Are you sure you want to permanently delete your account?"},
                  class: 'button' %>
    </nav>
  </footer>
</div>